// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token *string `json:"token"`
	User  *User   `json:"user"`
}

type Feed struct {
	Links []*Link `json:"links"`
	Count int     `json:"count"`
}

type Link struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	URL         string `json:"url"`
	PostedBy    *User  `json:"postedBy"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PostInput struct {
	URL         string `json:"url"`
	Description string `json:"description"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
