CREATE TABLE IF NOT EXISTS links(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  title VARCHAR (255),
  address VARCHAR (255),
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  PRIMARY KEY (id)
)