CREATE TABLE IF NOT EXISTS links(
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  description VARCHAR (255),
  url VARCHAR (255),
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  PRIMARY KEY (id)
)